version: '3'

services:

## PostgreSQL
  postgresql:
    container_name: postgres
    image: postgres:latest
    #restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      #- POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/data
